config/routes.rb
Calculator::Application.routes.draw do
  resources :kunals

  get "welcome/index"

root :to =>'welcome#index'

end

app/models/kunal.rb
class Kunal < ActiveRecord::Base
  attr_accessible :decription, :name, :title
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/kunals_controller.rb
class KunalsController < ApplicationController
  # GET /kunals
  # GET /kunals.json
  def index
    @kunals = Kunal.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @kunals }
    end
  end

  # GET /kunals/1
  # GET /kunals/1.json
  def show
    @kunal = Kunal.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @kunal }
    end
  end

  # GET /kunals/new
  # GET /kunals/new.json
  def new
    @kunal = Kunal.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @kunal }
    end
  end

  # GET /kunals/1/edit
  def edit
    @kunal = Kunal.find(params[:id])
  end

  # POST /kunals
  # POST /kunals.json
  def create
    @kunal = Kunal.new(params[:kunal])

    respond_to do |format|
      if @kunal.save
        format.html { redirect_to @kunal, notice: 'Kunal was successfully created.' }
        format.json { render json: @kunal, status: :created, location: @kunal }
      else
        format.html { render action: "new" }
        format.json { render json: @kunal.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /kunals/1
  # PUT /kunals/1.json
  def update
    @kunal = Kunal.find(params[:id])

    respond_to do |format|
      if @kunal.update_attributes(params[:kunal])
        format.html { redirect_to @kunal, notice: 'Kunal was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @kunal.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /kunals/1
  # DELETE /kunals/1.json
  def destroy
    @kunal = Kunal.find(params[:id])
    @kunal.destroy

    respond_to do |format|
      format.html { redirect_to kunals_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/kunals_helper.rb
module KunalsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/kunals/_form.html.erb
<%= form_for(@kunal) do |f| %>
  <% if @kunal.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@kunal.errors.count, "error") %> prohibited this kunal from being saved:</h2>

      <ul>
      <% @kunal.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :decription %><br />
    <%= f.text_area :decription %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/kunals/edit.html.erb
<h1>Editing kunal</h1>

<%= render 'form' %>

<%= link_to 'Show', @kunal %> |
<%= link_to 'Back', kunals_path %>

app/views/kunals/index.html.erb
<h1>Listing kunals</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Title</th>
    <th>Decription</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @kunals.each do |kunal| %>
  <tr>
    <td><%= kunal.name %></td>
    <td><%= kunal.title %></td>
    <td><%= kunal.decription %></td>
    <td><%= link_to 'Show', kunal %></td>
    <td><%= link_to 'Edit', edit_kunal_path(kunal) %></td>
    <td><%= link_to 'Destroy', kunal, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Kunal', new_kunal_path %>

app/views/kunals/new.html.erb
<h1>New kunal</h1>

<%= render 'form' %>

<%= link_to 'Back', kunals_path %>

app/views/kunals/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @kunal.name %>
</p>

<p>
  <b>Title:</b>
  <%= @kunal.title %>
</p>

<p>
  <b>Decription:</b>
  <%= @kunal.decription %>
</p>


<%= link_to 'Edit', edit_kunal_path(@kunal) %> |
<%= link_to 'Back', kunals_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Calculator</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/welcome/index.html.erb
<h1>Welcome#index</h1>

<%= link_to "Click Here", kunals_path %>